### ISSUE TITLE
Visualizer just keeps on endlessly loading.

### ISSUE THREAD

**Issue by hamslayer56** [Konsl/spicetify-visualizer#26]
I just installed it and it just keeps on loading and never loads in.
![imagen_2024-05-24_135839358](https://github.com/Konsl/spicetify-ncs-visualizer/assets/121444103/511ff362-7a7b-40ec-9e37-ef4d3e9b8aae)

**Comment by Konsl** [comment]
Are you on Spotify version `1.2.38.720`? In the last update, a few things got changed, which means even some core Spicetify functionality doesn't work yet. Apps that rely on those features won't work until Spicetify is updated.

If you want apps / extensions to work again as soon as possible, consider downgrading to the last version of Spotify. If you don't want to do that, your only option is to wait for the next Spicetify update.

**Comment by riptidee** [comment]
may i know how long until new spicetify update release?

**Comment by Konsl** [comment]
That's pretty much impossible to say at this point. Maybe a few days.
You can use [this version](https://github.com/Konsl/spicetify-ncs-visualizer/files/15448683/ncs-visualizer.zip) until the update is released. It doesn't support colors, but it is mostly stable aside from that.

**Comment by riptidee** [comment]
It works thanks!

**Comment by dracocraft** [comment]
> That's pretty much impossible to say at this point. Maybe a few days. You can use [this version](https://github.com/Konsl/spicetify-ncs-visualizer/files/15448683/ncs-visualizer.zip) until the update is released. It doesn't support colors, but it is mostly stable aside from that.

This makes my CPU go to 100% its that fixeable?

**Comment by Konsl** [comment]
Try [this](https://github.com/Konsl/spicetify-ncs-visualizer/files/15475099/dist.zip).
Functionally the same, but this one is not a debug build, so it's probably (?) more optimized.
Hope it helps.

**Comment by SkarletShadows** [comment]
GOAT, came here with the same question and am blessed. thank you Konsl

**Comment by hyunicode** [comment]
Spotify for macOS (Apple Silicon)
1.2.38.720.ga4a70a0e
Spicetify v2.36.12
Theme: Hazy / Base
Extensions: fullAppDisplay.js, adblock.js, cat-jam.js, theme.js
Custom apps: visualizer, marketplace, lyrics-plus

upgraded to latest spicitify, still endless loading, looking forwarding to ncs new release🫠🫠
<img width="1512" alt="image" src="https://github.com/Konsl/spicetify-ncs-visualizer/assets/81250265/2af91eb5-6a7d-455d-9472-771d34bc143e">

**Comment by hyunicode** [comment]
UPDATE

<img width="1512" alt="image" src="https://github.com/Konsl/spicetify-ncs-visualizer/assets/81250265/a7f1af27-c579-4a15-a09d-6d4eab04a631">


> Try [this](https://github.com/Konsl/spicetify-ncs-visualizer/files/15475099/dist.zip). Functionally the same, but this one is not a debug build, so it's probably (?) more optimized. Hope it helps.

it works!

**Comment by TheWolfCraft1** [comment]
I'm on windows 10 and both builds here are maxxing out my cpu at 100%. I know it's not a hardware issue, my cpu isn't _that_ old. 
I just had to reinstall spotify because it broke, and now it's on version 1.2.39.578, is there anything I can do?

**Comment by Konsl** [comment]
Just to confirm - you didn't experience the high CPU usage using the version with color, using the old Spotify?

**Comment by TheWolfCraft1** [comment]
I’m not able to run the most recent version(as of 2 days ago) and the two that are in here

**Comment by LuxxDevelopment** [comment]
For me the it also keeps loading in all 3 versions.

**Comment by Konsl** [comment]
The original version is working again on Spotify 1.2.41 / Spicetify 2.36.14.

**Comment by Konsl** [comment]
Apparently this is a problem again

**Comment by SirOaken** [comment]
can confirm. just downloaded and no load

**Comment by DMCK96** [comment]
Tried the updated version with no colour and the older version with colour. Neither are loading on Spicetify 2.38.4 and Spotify 1.2.48.405

**Comment by Konsl** [comment]
I just pushed an update, should be fixed.
