### ISSUE TITLE
my nsc visualizer not working

### ISSUE THREAD

**Issue by nadaviko15** [Konsl/spicetify-visualizer#28]
![Screenshot_15](https://github.com/Konsl/spicetify-ncs-visualizer/assets/59476653/59f38bb1-ce62-43da-aace-021e591f5927)

help?

**Comment by ejahdev** [comment]
![241004_12h33m22s_screenshot](https://github.com/user-attachments/assets/0595a342-f074-4825-8a5b-6e3bbc2360aa)
I'm currently having the same issue of just loading visualizer after newest spicetify/spotify updates

**Comment by Konsl** [comment]
See #26
