### ISSUE TITLE
custom app "visualiser" is not found

### ISSUE THREAD

**Issue by K4vin60** [Konsl/spicetify-visualizer#31]
Basically what you see here

![Screenshot 2024-08-13 202439](https://github.com/user-attachments/assets/ff81ff4d-95a2-4056-8a2b-73bb18ce6859)
![Screenshot 2024-08-13 202429](https://github.com/user-attachments/assets/77856728-0ed0-4977-9854-6713fa42a447)

**Comment by Konsl** [comment]
Please make sure the folder you extracted uses the same spelling as in the `spicetify config` command (i.e. `visualizer` or `visualiser` for both of them).

**Comment by K4vin60** [comment]
Thanks it worked immedieately, love the visualiser.


YOU darned americans 👆 /s
