### ISSUE TITLE
The Visualizer keeps loading 

### ISSUE THREAD

**Issue by Dimetro25** [Konsl/spicetify-visualizer#33]
The Visualizer keeps loading even after being updated 
![image](https://github.com/user-attachments/assets/38866ac8-0291-40f4-9402-6761458f74a9)

**Comment by ExoticCitron** [comment]
i got the same

**Comment by supergamer157** [comment]
me too

**Comment by supergamer157** [comment]
Downgrade Spotify to 1.2.42.290
https://spotify.en.uptodown.com/windows/download/1018977980

**Comment by ExoticCitron** [comment]
yeah, works, thanks!

**Comment by PixelSamRK** [comment]
@Konsl if we don't wanna downgrade Spotify, how do we solve this?

**Comment by Dimetro25** [comment]
Yes because I don't really want to downgrade it

**Comment by Konsl** [comment]
See #26
