### ISSUE TITLE
Doesn't work on Windows only

### ISSUE THREAD

**Issue by YoshiGamerFR** [Konsl/spicetify-visualizer#34]
I tried it on Linux, it works perfectly fine, while on Windows it just keeps loading.

**Comment by hyunicode** [comment]
same on Mac

**Comment by YoshiGamerFR** [comment]
That's pretty weird as I installed it on Linux (Zorin OS) and it works perfectly fine...

**Comment by Konsl** [comment]
The last Spotify update broke it, Linux is a bit behind on updates, so this is only a problem on Windows, see #26.
