### ISSUE TITLE
The visualizer lags the FUCK out of my client.

### ISSUE THREAD

**Issue by BoxingSnail** [Konsl/spicetify-visualizer#36]
Spotify runs at 2 FPS when I have the visualizer on.

**Comment by Fortress937** [comment]
Enabling Hardware Acceleration for spotify (spicetify) fixed an issue for me.

**Comment by Fortress937** [comment]
> Spotify runs at 2 FPS when I have the visualizer on.

Enabling Hardware Acceleration for spotify (spicetify) fixed an issue for me.

**Comment by Fortress937** [comment]
> Doesn't work. :P

Doesn't work? well lol :P
